errolinkQQ C:\★티스토리자동화\OneDrive-2025-02-28
errolinkQQ_page3 C:\★티스토리자동화\OneDrive-2025-02-28
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1111"     crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1111"     crossorigin="anonymous"></script>     crossorigin="anonymous"></script>
GPT-4o
Mychromecheck.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
내 크롬 버전 :: 135
RealchromeVersion.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
최신 크롬 버전 :: 135
driverVersion.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
내 드라이버 버전 :: 135
=========================================
내 크롬 버전 :: 135
최신 크롬 버전 :: 135
내 드라이버 버전 :: 135
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1111"     crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1111"     crossorigin="anonymous"></script>     crossorigin="anonymous"></script>
title 어린이 책임감, 선택과 행동을 완성하는 태도
IDPW 개수: 1
DB access----success!!
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
0
----------------------------import --------
에러메세지
list index out of range
0
----------------------------import --------
에러메세지
1
0
----------------------------import --------
에러메세지
2
0
----------------------------import --------
에러메세지
3
0
----------------------------import --------
에러메세지
4
0
----------------------------import --------
에러메세지
5
0
----------------------------import --------
에러메세지
6
0
----------------------------import --------
에러메세지
7
0
----------------------------import --------
에러메세지
8
0
----------------------------import --------
에러메세지
9
0
----------------------------import --------
에러메세지
10
0
----------------------------import --------
에러메세지
11
0
----------------------------import --------
에러메세지
12
0
----------------------------import --------
에러메세지
13
0
----------------------------import --------
에러메세지
14
0
----------------------------import --------
에러메세지
15
0
----------------------------import --------
에러메세지
16
0
----------------------------import --------
에러메세지
17
0
----------------------------import --------
에러메세지
18
0
----------------------------import --------
에러메세지
19
0
----------------------------import --------
에러메세지
20
0
----------------------------import --------
에러메세지
21
0
----------------------------import --------
에러메세지
22
0
----------------------------import --------
에러메세지
23
0
----------------------------import --------
에러메세지
24
0
----------------------------import --------
에러메세지
25
0
----------------------------import --------
에러메세지
26
0
----------------------------import --------
에러메세지
27
0
----------------------------import --------
에러메세지
28
0
----------------------------import --------
에러메세지
29
0
----------------------------import --------
에러메세지
30
0
----------------------------import --------
에러메세지
31
0
----------------------------import --------
에러메세지
32
0
----------------------------import --------
에러메세지
33
0
----------------------------import --------
에러메세지
34
0
----------------------------import --------
에러메세지
35
0
----------------------------import --------
에러메세지
36
0
----------------------------import --------
에러메세지
37
0
----------------------------import --------
에러메세지
38
0
----------------------------import --------
에러메세지
39
0
----------------------------import --------
에러메세지
40
0
----------------------------import --------
에러메세지
41
0
----------------------------import --------
에러메세지
42
0
----------------------------import --------
에러메세지
43
0
----------------------------import --------
에러메세지
44
0
----------------------------import --------
에러메세지
45
0
----------------------------import --------
에러메세지
46
0
----------------------------import --------
에러메세지
47
0
----------------------------import --------
에러메세지
48
0
----------------------------import --------
에러메세지
49
0
----------------------------import --------
에러메세지
50
0
----------------------------import --------
에러메세지
51
0
----------------------------import --------
에러메세지
52
0
----------------------------import --------
에러메세지
53
0
----------------------------import --------
에러메세지
54
0
----------------------------import --------
에러메세지
55
0
----------------------------import --------
에러메세지
56
0
----------------------------import --------
에러메세지
57
0
----------------------------import --------
에러메세지
58
0
----------------------------import --------
에러메세지
59
0
----------------------------import --------
에러메세지
60
0
----------------------------import --------
에러메세지
61
0
----------------------------import --------
에러메세지
62
0
----------------------------import --------
에러메세지
63
0
----------------------------import --------
에러메세지
64
0
----------------------------import --------
에러메세지
65
0
----------------------------import --------
에러메세지
66
0
----------------------------import --------
에러메세지
67
0
----------------------------import --------
에러메세지
68
0
----------------------------import --------
에러메세지
69
0
----------------------------import --------
에러메세지
70
0
----------------------------import --------
에러메세지
71
0
----------------------------import --------
에러메세지
72
0
----------------------------import --------
에러메세지
73
0
----------------------------import --------
에러메세지
74
0
----------------------------import --------
에러메세지
75
0
----------------------------import --------
에러메세지
76
0
----------------------------import --------
에러메세지
77
0
----------------------------import --------
에러메세지
78
0
----------------------------import --------
에러메세지
79
0
----------------------------import --------
에러메세지
80
0
----------------------------import --------
에러메세지
81
0
----------------------------import --------
에러메세지
82
0
----------------------------import --------
에러메세지
83
0
----------------------------import --------
에러메세지
84
0
----------------------------import --------
에러메세지
85
0
----------------------------import --------
에러메세지
86
0
----------------------------import --------
에러메세지
87
0
----------------------------import --------
에러메세지
88
0
----------------------------import --------
에러메세지
89
0
----------------------------import --------
에러메세지
90
0
----------------------------import --------
에러메세지
91
0
----------------------------import --------
에러메세지
92
0
----------------------------import --------
에러메세지
93
0
----------------------------import --------
에러메세지
94
0
----------------------------import --------
에러메세지
95
0
----------------------------import --------
에러메세지
96
0
----------------------------import --------
에러메세지
97
0
----------------------------import --------
에러메세지
98
0
----------------------------import --------
에러메세지
99
0
----------------------------import --------
에러메세지
100
0
----------------------------import --------
에러메세지
101
0
----------------------------import --------
에러메세지
102
0
----------------------------import --------
에러메세지
103
0
----------------------------import --------
에러메세지
104
0
----------------------------import --------
에러메세지
105
0
----------------------------import --------
에러메세지
106
0
----------------------------import --------
에러메세지
107
0
----------------------------import --------
에러메세지
108
0
----------------------------import --------
에러메세지
109
0
----------------------------import --------
에러메세지
110
0
----------------------------import --------
에러메세지
111
0
----------------------------import --------
에러메세지
112
0
----------------------------import --------
에러메세지
113
0
----------------------------import --------
에러메세지
114
0
----------------------------import --------
에러메세지
115
0
----------------------------import --------
에러메세지
116
0
----------------------------import --------
에러메세지
117
0
----------------------------import --------
에러메세지
118
0
----------------------------import --------
에러메세지
119
0
----------------------------import --------
에러메세지
120
0
----------------------------import --------
에러메세지
121
0
----------------------------import --------
에러메세지
122
0
----------------------------import --------
에러메세지
123
0
----------------------------import --------
에러메세지
124
0
----------------------------import --------
에러메세지
125
0
----------------------------import --------
에러메세지
126
0
----------------------------import --------
에러메세지
127
0
----------------------------import --------
에러메세지
128
0
----------------------------import --------
에러메세지
129
0
----------------------------import --------
에러메세지
130
0
----------------------------import --------
에러메세지
131
0
----------------------------import --------
에러메세지
132
0
----------------------------import --------
에러메세지
133
0
----------------------------import --------
에러메세지
134
0
----------------------------import --------
에러메세지
135
0
----------------------------import --------
에러메세지
136
0
----------------------------import --------
에러메세지
137
0
----------------------------import --------
에러메세지
138
0
----------------------------import --------
에러메세지
139
0
----------------------------import --------
에러메세지
140
0
----------------------------import --------
에러메세지
141
0
----------------------------import --------
에러메세지
142
0
----------------------------import --------
에러메세지
143
0
----------------------------import --------
에러메세지
144
0
----------------------------import --------
에러메세지
145
0
----------------------------import --------
에러메세지
146
0
----------------------------import --------
에러메세지
147
0
----------------------------import --------
에러메세지
148
0
----------------------------import --------
에러메세지
149
0
----------------------------import --------
에러메세지
150
0
----------------------------import --------
에러메세지
151
0
----------------------------import --------
에러메세지
152
0
----------------------------import --------
에러메세지
153
0
----------------------------import --------
에러메세지
154
0
----------------------------import --------
에러메세지
155
0
----------------------------import --------
에러메세지
156
0
----------------------------import --------
에러메세지
157
0
----------------------------import --------
에러메세지
158
0
----------------------------import --------
에러메세지
159
0
----------------------------import --------
에러메세지
160
0
----------------------------import --------
에러메세지
161
0
----------------------------import --------
에러메세지
162
0
----------------------------import --------
에러메세지
163
0
----------------------------import --------
에러메세지
164
0
----------------------------import --------
에러메세지
165
0
----------------------------import --------
에러메세지
166
0
----------------------------import --------
에러메세지
167
0
----------------------------import --------
에러메세지
168
0
----------------------------import --------
에러메세지
169
0
----------------------------import --------
에러메세지
170
0
----------------------------import --------
에러메세지
171
0
----------------------------import --------
에러메세지
172
0
----------------------------import --------
에러메세지
173
0
----------------------------import --------
에러메세지
174
0
----------------------------import --------
에러메세지
175
0
----------------------------import --------
에러메세지
176
0
----------------------------import --------
에러메세지
177
0
----------------------------import --------
에러메세지
178
0
----------------------------import --------
에러메세지
179
0
----------------------------import --------
에러메세지
180
0
----------------------------import --------
에러메세지
181
0
----------------------------import --------
에러메세지
182
0
----------------------------import --------
에러메세지
183
0
----------------------------import --------
에러메세지
184
0
----------------------------import --------
에러메세지
185
0
----------------------------import --------
에러메세지
186
0
----------------------------import --------
에러메세지
187
0
----------------------------import --------
에러메세지
188
0
----------------------------import --------
에러메세지
189
0
----------------------------import --------
에러메세지
190
0
----------------------------import --------
에러메세지
191
0
----------------------------import --------
에러메세지
192
0
----------------------------import --------
에러메세지
193
0
----------------------------import --------
에러메세지
194
0
----------------------------import --------
에러메세지
195
0
----------------------------import --------
에러메세지
196
0
----------------------------import --------
에러메세지
197
0
----------------------------import --------
에러메세지
198
0
----------------------------import --------
에러메세지
199
0
----------------------------import --------
에러메세지
200
0
----------------------------import --------
에러메세지
201
0
----------------------------import --------
에러메세지
202
0
----------------------------import --------
에러메세지
203
0
----------------------------import --------
에러메세지
204
0
----------------------------import --------
에러메세지
205
0
----------------------------import --------
에러메세지
206
0
----------------------------import --------
에러메세지
207
0
----------------------------import --------
에러메세지
208
0
----------------------------import --------
에러메세지
209
0
----------------------------import --------
에러메세지
210
0
----------------------------import --------
에러메세지
211
0
----------------------------import --------
에러메세지
212
0
----------------------------import --------
에러메세지
213
0
----------------------------import --------
에러메세지
214
0
----------------------------import --------
에러메세지
215
0
----------------------------import --------
에러메세지
216
0
----------------------------import --------
에러메세지
217
0
----------------------------import --------
에러메세지
218
0
----------------------------import --------
에러메세지
219
0
----------------------------import --------
에러메세지
220
0
----------------------------import --------
에러메세지
221
0
----------------------------import --------
에러메세지
222
0
----------------------------import --------
에러메세지
223
0
----------------------------import --------
에러메세지
224
0
----------------------------import --------
에러메세지
225
0
----------------------------import --------
에러메세지
226
0
----------------------------import --------
에러메세지
227
0
----------------------------import --------
에러메세지
228
0
----------------------------import --------
에러메세지
229
0
----------------------------import --------
에러메세지
230
0
----------------------------import --------
에러메세지
231
0
----------------------------import --------
에러메세지
232
0
----------------------------import --------
에러메세지
233
0
----------------------------import --------
에러메세지
234
0
----------------------------import --------
에러메세지
235
0
----------------------------import --------
에러메세지
236
0
----------------------------import --------
에러메세지
237
0
----------------------------import --------
에러메세지
238
0
----------------------------import --------
에러메세지
239
0
----------------------------import --------
에러메세지
240
0
----------------------------import --------
에러메세지
241
0
----------------------------import --------
에러메세지
242
0
----------------------------import --------
에러메세지
243
0
----------------------------import --------
에러메세지
244
0
----------------------------import --------
에러메세지
245
0
----------------------------import --------
에러메세지
246
0
----------------------------import --------
에러메세지
247
0
----------------------------import --------
에러메세지
248
0
----------------------------import --------
에러메세지
249
0
----------------------------import --------
에러메세지
250
0
----------------------------import --------
에러메세지
251
0
----------------------------import --------
에러메세지
252
0
----------------------------import --------
에러메세지
253
0
----------------------------import --------
에러메세지
254
0
----------------------------import --------
에러메세지
255
0
----------------------------import --------
에러메세지
256
0
----------------------------import --------
에러메세지
257
0
----------------------------import --------
에러메세지
258
0
----------------------------import --------
에러메세지
259
0
----------------------------import --------
에러메세지
260
0
----------------------------import --------
에러메세지
261
0
----------------------------import --------
에러메세지
262
0
----------------------------import --------
에러메세지
263
0
----------------------------import --------
에러메세지
264
0
----------------------------import --------
에러메세지
265
0
----------------------------import --------
에러메세지
266
0
----------------------------import --------
에러메세지
267
0
----------------------------import --------
에러메세지
268
0
----------------------------import --------
에러메세지
269
0
----------------------------import --------
에러메세지
270
0
----------------------------import --------
에러메세지
271
0
----------------------------import --------
에러메세지
272
0
----------------------------import --------
에러메세지
273
0
----------------------------import --------
에러메세지
274
0
----------------------------import --------
에러메세지
275
0
----------------------------import --------
에러메세지
276
0
----------------------------import --------
에러메세지
277
0
----------------------------import --------
에러메세지
278
0
----------------------------import --------
에러메세지
279
0
----------------------------import --------
에러메세지
280
0
----------------------------import --------
에러메세지
281
0
----------------------------import --------
에러메세지
282
0
----------------------------import --------
에러메세지
283
0
----------------------------import --------
에러메세지
284
0
----------------------------import --------
에러메세지
285
0
----------------------------import --------
에러메세지
286
0
----------------------------import --------
에러메세지
287
0
----------------------------import --------
에러메세지
288
0
----------------------------import --------
에러메세지
289
0
----------------------------import --------
에러메세지
290
0
----------------------------import --------
에러메세지
291
0
----------------------------import --------
에러메세지
292
0
----------------------------import --------
에러메세지
293
0
----------------------------import --------
에러메세지
294
0
----------------------------import --------
에러메세지
295
0
----------------------------import --------
에러메세지
296
0
----------------------------import --------
에러메세지
297
0
----------------------------import --------
에러메세지
298
0
----------------------------import --------
에러메세지
299
0
----------------------------import --------
에러메세지
300
0
----------------------------import --------
에러메세지
301
0
----------------------------import --------
에러메세지
302
0
----------------------------import --------
에러메세지
303
0
----------------------------import --------
에러메세지
304
0
----------------------------import --------
에러메세지
305
0
----------------------------import --------
에러메세지
306
0
----------------------------import --------
에러메세지
307
0
----------------------------import --------
에러메세지
308
0
----------------------------import --------
에러메세지
309
0
----------------------------import --------
에러메세지
310
0
----------------------------import --------
에러메세지
311
0
----------------------------import --------
에러메세지
312
0
----------------------------import --------
에러메세지
313
0
----------------------------import --------
에러메세지
314
0
----------------------------import --------
에러메세지
315
0
----------------------------import --------
에러메세지
316
0
----------------------------import --------
에러메세지
317
0
----------------------------import --------
에러메세지
318
0
----------------------------import --------
에러메세지
319
0
----------------------------import --------
에러메세지
320
0
----------------------------import --------
에러메세지
321
0
----------------------------import --------
에러메세지
322
0
----------------------------import --------
에러메세지
323
0
----------------------------import --------
에러메세지
324
0
----------------------------import --------
에러메세지
325
0
----------------------------import --------
에러메세지
326
0
----------------------------import --------
에러메세지
327
0
----------------------------import --------
에러메세지
328
0
----------------------------import --------
에러메세지
329
0
----------------------------import --------
에러메세지
330
0
----------------------------import --------
에러메세지
331
0
----------------------------import --------
에러메세지
332
0
----------------------------import --------
에러메세지
333
0
----------------------------import --------
에러메세지
334
0
----------------------------import --------
에러메세지
335
0
----------------------------import --------
에러메세지
336
0
----------------------------import --------
에러메세지
337
0
----------------------------import --------
에러메세지
338
0
----------------------------import --------
에러메세지
339
0
----------------------------import --------
에러메세지
340
0
----------------------------import --------
에러메세지
341
0
----------------------------import --------
에러메세지
342
0
----------------------------import --------
에러메세지
343
0
----------------------------import --------
에러메세지
344
0
----------------------------import --------
에러메세지
345
0
----------------------------import --------
에러메세지
346
0
----------------------------import --------
에러메세지
347
0
----------------------------import --------
에러메세지
348
0
----------------------------import --------
에러메세지
349
0
----------------------------import --------
에러메세지
350
0
----------------------------import --------
에러메세지
351
0
----------------------------import --------
에러메세지
352
0
----------------------------import --------
에러메세지
353
0
----------------------------import --------
에러메세지
354
0
----------------------------import --------
에러메세지
355
0
----------------------------import --------
에러메세지
356
0
----------------------------import --------
에러메세지
357
0
----------------------------import --------
에러메세지
358
0
----------------------------import --------
에러메세지
359
0
----------------------------import --------
에러메세지
360
0
----------------------------import --------
에러메세지
361
0
----------------------------import --------
에러메세지
362
0
----------------------------import --------
에러메세지
363
0
----------------------------import --------
에러메세지
364
0
----------------------------import --------
에러메세지
365
0
----------------------------import --------
에러메세지
366
0
----------------------------import --------
에러메세지
367
0
----------------------------import --------
에러메세지
368
0
----------------------------import --------
에러메세지
369
0
----------------------------import --------
에러메세지
370
0
----------------------------import --------
에러메세지
371
0
----------------------------import --------
에러메세지
372
0
----------------------------import --------
에러메세지
373
0
----------------------------import --------
에러메세지
374
0
----------------------------import --------
에러메세지
375
0
----------------------------import --------
에러메세지
376
0
----------------------------import --------
에러메세지
377
0
----------------------------import --------
에러메세지
378
0
----------------------------import --------
에러메세지
379
0
----------------------------import --------
에러메세지
380
0
----------------------------import --------
에러메세지
381
0
----------------------------import --------
에러메세지
382
0
----------------------------import --------
에러메세지
383
0
----------------------------import --------
에러메세지
384
0
----------------------------import --------
에러메세지
385
0
----------------------------import --------
에러메세지
386
0
----------------------------import --------
에러메세지
387
0
----------------------------import --------
에러메세지
388
0
----------------------------import --------
에러메세지
389
0
----------------------------import --------
에러메세지
390
0
----------------------------import --------
에러메세지
391
0
----------------------------import --------
에러메세지
392
0
----------------------------import --------
에러메세지
393
0
----------------------------import --------
에러메세지
394
0
----------------------------import --------
에러메세지
395
0
----------------------------import --------
에러메세지
396
0
----------------------------import --------
에러메세지
397
0
----------------------------import --------
에러메세지
398
0
----------------------------import --------
에러메세지
399
0
----------------------------import --------
에러메세지
400
0
----------------------------import --------
에러메세지
401
0
----------------------------import --------
에러메세지
402
0
----------------------------import --------
에러메세지
403
0
----------------------------import --------
에러메세지
404
0
----------------------------import --------
에러메세지
405
0
----------------------------import --------
에러메세지
406
0
----------------------------import --------
에러메세지
407
0
----------------------------import --------
에러메세지
408
0
----------------------------import --------
에러메세지
409
0
----------------------------import --------
에러메세지
410
0
----------------------------import --------
에러메세지
411
0
----------------------------import --------
에러메세지
412
0
----------------------------import --------
에러메세지
413
0
----------------------------import --------
에러메세지
414
0
----------------------------import --------
에러메세지
415
0
----------------------------import --------
에러메세지
416
0
----------------------------import --------
에러메세지
417
0
----------------------------import --------
에러메세지
418
0
----------------------------import --------
에러메세지
419
0
----------------------------import --------
에러메세지
420
0
----------------------------import --------
에러메세지
421
0
----------------------------import --------
에러메세지
422
0
----------------------------import --------
에러메세지
423
0
----------------------------import --------
에러메세지
424
0
----------------------------import --------
에러메세지
425
0
----------------------------import --------
에러메세지
426
0
----------------------------import --------
에러메세지
427
0
----------------------------import --------
에러메세지
428
0
----------------------------import --------
에러메세지
429
0
----------------------------import --------
에러메세지
430
0
----------------------------import --------
에러메세지
431
0
----------------------------import --------
에러메세지
432
0
----------------------------import --------
에러메세지
433
0
----------------------------import --------
에러메세지
434
0
----------------------------import --------
에러메세지
435
0
----------------------------import --------
에러메세지
436
0
----------------------------import --------
에러메세지
437
0
----------------------------import --------
에러메세지
438
0
----------------------------import --------
에러메세지
439
0
----------------------------import --------
에러메세지
440
0
----------------------------import --------
에러메세지
441
0
----------------------------import --------
에러메세지
442
0
----------------------------import --------
에러메세지
443
0
----------------------------import --------
에러메세지
444
0
----------------------------import --------
에러메세지
445
0
----------------------------import --------
에러메세지
446
0
----------------------------import --------
에러메세지
447
0
----------------------------import --------
에러메세지
448
0
----------------------------import --------
에러메세지
449
0
----------------------------import --------
에러메세지
450
0
----------------------------import --------
에러메세지
451
0
----------------------------import --------
에러메세지
452
0
----------------------------import --------
에러메세지
453
0
----------------------------import --------
에러메세지
454
0
----------------------------import --------
에러메세지
455
0
----------------------------import --------
에러메세지
456
0
----------------------------import --------
에러메세지
457
0
----------------------------import --------
에러메세지
458
0
----------------------------import --------
에러메세지
459
0
----------------------------import --------
에러메세지
460
0
----------------------------import --------
에러메세지
461
0
----------------------------import --------
에러메세지
462
0
----------------------------import --------
에러메세지
463
0
----------------------------import --------
에러메세지
464
0
----------------------------import --------
에러메세지
465
0
----------------------------import --------
에러메세지
466
0
----------------------------import --------
에러메세지
467
0
----------------------------import --------
에러메세지
468
0
----------------------------import --------
에러메세지
469
0
----------------------------import --------
에러메세지
470
0
----------------------------import --------
에러메세지
471
0
----------------------------import --------
에러메세지
472
0
----------------------------import --------
에러메세지
473
0
----------------------------import --------
에러메세지
474
0
----------------------------import --------
에러메세지
475
0
----------------------------import --------
에러메세지
476
0
----------------------------import --------
에러메세지
477
0
----------------------------import --------
에러메세지
478
0
----------------------------import --------
에러메세지
479
0
----------------------------import --------
에러메세지
480
0
----------------------------import --------
에러메세지
481
0
----------------------------import --------
에러메세지
482
0
----------------------------import --------
에러메세지
483
0
----------------------------import --------
에러메세지
484
0
----------------------------import --------
에러메세지
485
0
----------------------------import --------
에러메세지
486
0
----------------------------import --------
에러메세지
487
0
----------------------------import --------
에러메세지
488
0
----------------------------import --------
에러메세지
489
0
----------------------------import --------
에러메세지
490
0
----------------------------import --------
에러메세지
491
0
----------------------------import --------
에러메세지
492
0
----------------------------import --------
에러메세지
493
0
----------------------------import --------
에러메세지
494
0
----------------------------import --------
에러메세지
495
0
----------------------------import --------
에러메세지
496
0
----------------------------import --------
에러메세지
497
0
----------------------------import --------
에러메세지
498
0
----------------------------import --------
에러메세지
499
0
----------------------------import --------
에러메세지
500
0
----------------------------import --------
에러메세지
501
0
----------------------------import --------
에러메세지
502
0
----------------------------import --------
에러메세지
503
0
----------------------------import --------
에러메세지
504
0
----------------------------import --------
에러메세지
505
0
----------------------------import --------
에러메세지
506
0
----------------------------import --------
에러메세지
507
0
----------------------------import --------
에러메세지
508
0
----------------------------import --------
에러메세지
509
0
----------------------------import --------
에러메세지
510
0
----------------------------import --------
에러메세지
511
0
----------------------------import --------
에러메세지
512
0
----------------------------import --------
에러메세지
513
0
----------------------------import --------
에러메세지
514
0
----------------------------import --------
에러메세지
515
0
----------------------------import --------
에러메세지
516
0
----------------------------import --------
에러메세지
517
0
----------------------------import --------
에러메세지
518
0
----------------------------import --------
에러메세지
519
0
----------------------------import --------
에러메세지
520
0
----------------------------import --------
에러메세지
521
0
----------------------------import --------
에러메세지
522
0
----------------------------import --------
에러메세지
523
0
----------------------------import --------
에러메세지
524
0
----------------------------import --------
에러메세지
525
0
----------------------------import --------
에러메세지
526
0
----------------------------import --------
에러메세지
527
0
----------------------------import --------
에러메세지
528
0
----------------------------import --------
에러메세지
529
0
----------------------------import --------
에러메세지
530
0
----------------------------import --------
에러메세지
531
0
----------------------------import --------
에러메세지
532
0
----------------------------import --------
에러메세지
533
0
----------------------------import --------
에러메세지
534
0
----------------------------import --------
에러메세지
535
0
----------------------------import --------
에러메세지
536
0
----------------------------import --------
에러메세지
537
0
----------------------------import --------
에러메세지
538
0
----------------------------import --------
에러메세지
539
0
----------------------------import --------
에러메세지
540
0
----------------------------import --------
에러메세지
541
0
----------------------------import --------
에러메세지
542
0
----------------------------import --------
에러메세지
543
0
----------------------------import --------
에러메세지
544
0
----------------------------import --------
에러메세지
545
0
----------------------------import --------
에러메세지
546
0
----------------------------import --------
에러메세지
547
0
----------------------------import --------
에러메세지
548
0
----------------------------import --------
에러메세지
549
0
----------------------------import --------
에러메세지
550
0
----------------------------import --------
에러메세지
551
0
----------------------------import --------
에러메세지
552
0
----------------------------import --------
에러메세지
553
0
----------------------------import --------
에러메세지
554
0
----------------------------import --------
에러메세지
555
0
----------------------------import --------
에러메세지
556
0
----------------------------import --------
에러메세지
557
0
----------------------------import --------
에러메세지
558
0
----------------------------import --------
에러메세지
559
0
----------------------------import --------
에러메세지
560
0
----------------------------import --------
에러메세지
561
0
----------------------------import --------
에러메세지
562
0
----------------------------import --------
에러메세지
563
0
----------------------------import --------
에러메세지
564
0
----------------------------import --------
에러메세지
565
0
----------------------------import --------
에러메세지
566
0
----------------------------import --------
에러메세지
567
0
----------------------------import --------
에러메세지
568
0
----------------------------import --------
에러메세지
569
0
----------------------------import --------
에러메세지
570
0
----------------------------import --------
에러메세지
571
0
----------------------------import --------
에러메세지
572
0
----------------------------import --------
에러메세지
573
0
----------------------------import --------
에러메세지
574
0
----------------------------import --------
에러메세지
575
0
----------------------------import --------
에러메세지
576
0
----------------------------import --------
에러메세지
577
0
----------------------------import --------
에러메세지
578
0
----------------------------import --------
에러메세지
579
0
----------------------------import --------
에러메세지
580
0
----------------------------import --------
에러메세지
581
0
----------------------------import --------
에러메세지
582
0
----------------------------import --------
에러메세지
583
0
----------------------------import --------
에러메세지
584
0
----------------------------import --------
에러메세지
585
0
----------------------------import --------
에러메세지
586
0
----------------------------import --------
에러메세지
587
0
----------------------------import --------
에러메세지
588
0
----------------------------import --------
에러메세지
589
0
----------------------------import --------
에러메세지
590
0
----------------------------import --------
에러메세지
591
0
----------------------------import --------
에러메세지
592
0
----------------------------import --------
에러메세지
593
0
----------------------------import --------
에러메세지
594
0
----------------------------import --------
에러메세지
595
0
----------------------------import --------
에러메세지
596
0
----------------------------import --------
에러메세지
597
0
----------------------------import --------
에러메세지
598
0
----------------------------import --------
에러메세지
599
0
----------------------------import --------
에러메세지
600
0
----------------------------import --------
에러메세지
601
0
----------------------------import --------
에러메세지
602
0
----------------------------import --------
에러메세지
603
0
----------------------------import --------
에러메세지
604
0
----------------------------import --------
에러메세지
605
0
----------------------------import --------
에러메세지
606
0
----------------------------import --------
에러메세지
607
0
----------------------------import --------
에러메세지
608
0
----------------------------import --------
에러메세지
609
0
----------------------------import --------
에러메세지
610
0
----------------------------import --------
에러메세지
611
0
----------------------------import --------
에러메세지
612
0
----------------------------import --------
에러메세지
613
0
----------------------------import --------
에러메세지
614
0
----------------------------import --------
에러메세지
615
0
----------------------------import --------
에러메세지
616
0
----------------------------import --------
에러메세지
617
0
----------------------------import --------
에러메세지
618
0
----------------------------import --------
에러메세지
619
0
----------------------------import --------
에러메세지
620
0
----------------------------import --------
에러메세지
621
0
----------------------------import --------
에러메세지
622
0
----------------------------import --------
에러메세지
623
0
----------------------------import --------
에러메세지
624
0
----------------------------import --------
에러메세지
625
0
----------------------------import --------
에러메세지
626
0
----------------------------import --------
에러메세지
627
0
----------------------------import --------
에러메세지
628
0
----------------------------import --------
에러메세지
629
0
----------------------------import --------
에러메세지
630
0
----------------------------import --------
에러메세지
631
0
----------------------------import --------
에러메세지
632
0
----------------------------import --------
에러메세지
633
0
----------------------------import --------
에러메세지
634
0
----------------------------import --------
에러메세지
635
0
----------------------------import --------
에러메세지
636
0
----------------------------import --------
에러메세지
637
0
----------------------------import --------
에러메세지
638
0
----------------------------import --------
에러메세지
639
0
----------------------------import --------
에러메세지
640
GPT-3.5
0
----------------------------import --------
에러메세지
641
0
----------------------------import --------
에러메세지
642
0
----------------------------import --------
에러메세지
643
0
----------------------------import --------
에러메세지
644
0
----------------------------import --------
에러메세지
645
0
----------------------------import --------
에러메세지
646
0
----------------------------import --------
에러메세지
647
0
----------------------------import --------
에러메세지
648
0
----------------------------import --------
에러메세지
649
0
----------------------------import --------
에러메세지
650
0
----------------------------import --------
에러메세지
651
0
----------------------------import --------
에러메세지
652
0
----------------------------import --------
에러메세지
653
0
----------------------------import --------
에러메세지
654
0
----------------------------import --------
에러메세지
655
0
----------------------------import --------
에러메세지
656
0
----------------------------import --------
에러메세지
657
0
----------------------------import --------
에러메세지
658
0
----------------------------import --------
에러메세지
659
0
----------------------------import --------
에러메세지
660
0
----------------------------import --------
에러메세지
661
0
----------------------------import --------
에러메세지
662
0
----------------------------import --------
에러메세지
663
Mychromecheck.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
0
----------------------------import --------
에러메세지
664
0
----------------------------import --------
에러메세지
665
0
----------------------------import --------
에러메세지
666
Captured output: Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 664

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 664
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 665

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 665
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 666

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 666
135
내 크롬 버전 :: Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 664

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 664
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 665

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 665
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 666

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 666
135
RealchromeVersion.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
최신 크롬 버전 :: 135
driverVersion.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
0
----------------------------import --------
에러메세지
667
0
----------------------------import --------
에러메세지
668
0
----------------------------import --------
에러메세지
669
0
----------------------------import --------
에러메세지
670
0
----------------------------import --------
에러메세지
671
0
----------------------------import --------
에러메세지
672
0
----------------------------import --------
에러메세지
673
0
----------------------------import --------
에러메세지
674
0
----------------------------import --------
에러메세지
675
Captured output: Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 667

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 667
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 668

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 668
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 669

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 669
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 670

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 670
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 671

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 671
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 672

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 672
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 673

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 673
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 674

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 674
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 675

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 675
135
내 드라이버 버전 :: Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 667

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 667
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 668

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 668
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 669

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 669
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 670

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 670
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 671

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 671
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 672

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 672
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 673

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 673
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 674

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 674
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 675

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 675
135
=========================================
내 크롬 버전 :: Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 664

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 664
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 665

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 665
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 666

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 666
135
최신 크롬 버전 :: 135
내 드라이버 버전 :: Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 667

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 667
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 668

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 668
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 669

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 669
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 670

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 670
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 671

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 671
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 672

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 672
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 673

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 673
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 674

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 674
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3803, in get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 675

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Premium_tistory_V2.65.py", line 7837, in resevation_excel
  File "pandas\core\series.py", line 981, in __getitem__
  File "pandas\core\series.py", line 1089, in _get_value
  File "pandas\core\indexes\base.py", line 3805, in get_loc
KeyError: 675
135
크롬드라이버 강제 종료 성공
크롬드라이버 강제 종료 성공
Mychromecheck.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
내 크롬 버전 :: 135
RealchromeVersion.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
최신 크롬 버전 :: 135
driverVersion.cp310-win_amd64.pyd already exists locally.
Running main() from the .pyd file...
Captured output: 135
내 드라이버 버전 :: 135
=========================================
내 크롬 버전 :: 135
최신 크롬 버전 :: 135
내 드라이버 버전 :: 135
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1111"     crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1111"     crossorigin="anonymous"></script>     crossorigin="anonymous"></script>
title 어린이 책임감, 선택과 행동을 완성하는 태도
IDPW 개수: 1
DB access----success!!
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
0
----------------------------import --------
에러메세지
list index out of range
0
----------------------------import --------
에러메세지
1
0
----------------------------import --------
에러메세지
2
0
----------------------------import --------
에러메세지
3
0
----------------------------import --------
에러메세지
4
0
----------------------------import --------
에러메세지
5
0
----------------------------import --------
에러메세지
6
0
----------------------------import --------
에러메세지
7
0
----------------------------import --------
에러메세지
8
0
----------------------------import --------
에러메세지
9
0
----------------------------import --------
에러메세지
10
0
----------------------------import --------
에러메세지
11
0
----------------------------import --------
에러메세지
12
0
----------------------------import --------
에러메세지
13
0
----------------------------import --------
에러메세지
14
0
----------------------------import --------
에러메세지
15
0
----------------------------import --------
에러메세지
16
0
----------------------------import --------
에러메세지
17
0
----------------------------import --------
에러메세지
18
0
----------------------------import --------
에러메세지
19
0
----------------------------import --------
에러메세지
20
0
----------------------------import --------
에러메세지
21
0
----------------------------import --------
에러메세지
22
0
----------------------------import --------
에러메세지
23
0
----------------------------import --------
에러메세지
24
0
----------------------------import --------
에러메세지
25
0
----------------------------import --------
에러메세지
26
0
----------------------------import --------
에러메세지
27
0
----------------------------import --------
에러메세지
28
0
----------------------------import --------
에러메세지
29
0
----------------------------import --------
에러메세지
30
0
----------------------------import --------
에러메세지
31
0
----------------------------import --------
에러메세지
32
0
----------------------------import --------
에러메세지
33
0
----------------------------import --------
에러메세지
34
0
----------------------------import --------
에러메세지
35
0
----------------------------import --------
에러메세지
36
0
----------------------------import --------
에러메세지
37
0
----------------------------import --------
에러메세지
38
0
----------------------------import --------
에러메세지
39
0
----------------------------import --------
에러메세지
40
0
----------------------------import --------
에러메세지
41
0
----------------------------import --------
에러메세지
42
0
----------------------------import --------
에러메세지
43
0
----------------------------import --------
에러메세지
44
0
----------------------------import --------
에러메세지
45
0
----------------------------import --------
에러메세지
46
0
----------------------------import --------
에러메세지
47
0
----------------------------import --------
에러메세지
48
0
----------------------------import --------
에러메세지
49
0
----------------------------import --------
에러메세지
50
0
----------------------------import --------
에러메세지
51
0
----------------------------import --------
에러메세지
52
0
----------------------------import --------
에러메세지
53
0
----------------------------import --------
에러메세지
54
0
----------------------------import --------
에러메세지
55
0
----------------------------import --------
에러메세지
56
0
----------------------------import --------
에러메세지
57
0
----------------------------import --------
에러메세지
58
0
----------------------------import --------
에러메세지
59
0
----------------------------import --------
에러메세지
60
0
----------------------------import --------
에러메세지
61
0
----------------------------import --------
에러메세지
62
0
----------------------------import --------
에러메세지
63
0
----------------------------import --------
에러메세지
64
0
----------------------------import --------
에러메세지
65
0
----------------------------import --------
에러메세지
66
0
----------------------------import --------
에러메세지
67
0
----------------------------import --------
에러메세지
68
0
----------------------------import --------
에러메세지
69
0
----------------------------import --------
에러메세지
70
0
----------------------------import --------
에러메세지
71
0
----------------------------import --------
에러메세지
72
0
----------------------------import --------
에러메세지
73
0
----------------------------import --------
에러메세지
74
0
----------------------------import --------
에러메세지
75
0
----------------------------import --------
에러메세지
76
0
----------------------------import --------
에러메세지
77
0
----------------------------import --------
에러메세지
78
0
----------------------------import --------
에러메세지
79
0
----------------------------import --------
에러메세지
80
0
----------------------------import --------
에러메세지
81
0
----------------------------import --------
에러메세지
82
0
----------------------------import --------
에러메세지
83
0
----------------------------import --------
에러메세지
84
0
----------------------------import --------
에러메세지
85
0
----------------------------import --------
에러메세지
86
0
----------------------------import --------
에러메세지
87
0
----------------------------import --------
에러메세지
88
0
----------------------------import --------
에러메세지
89
0
----------------------------import --------
에러메세지
90
0
----------------------------import --------
에러메세지
91
0
----------------------------import --------
에러메세지
92
0
----------------------------import --------
에러메세지
93
0
----------------------------import --------
에러메세지
94
0
----------------------------import --------
에러메세지
95
0
----------------------------import --------
에러메세지
96
0
----------------------------import --------
에러메세지
97
0
----------------------------import --------
에러메세지
98
0
----------------------------import --------
에러메세지
99
0
----------------------------import --------
에러메세지
100
0
----------------------------import --------
에러메세지
101
0
----------------------------import --------
에러메세지
102
0
----------------------------import --------
에러메세지
103
0
----------------------------import --------
에러메세지
104
0
----------------------------import --------
에러메세지
105
0
----------------------------import --------
에러메세지
106
0
----------------------------import --------
에러메세지
107
0
----------------------------import --------
에러메세지
108
0
----------------------------import --------
에러메세지
109
0
----------------------------import --------
에러메세지
110
0
----------------------------import --------
에러메세지
111
0
----------------------------import --------
에러메세지
112
0
----------------------------import --------
에러메세지
113
0
----------------------------import --------
에러메세지
114
시작
0
----------------------------import --------
에러메세지
115
File saved to: C:\★티스토리자동화\OneDrive-2025-02-28\logfile.txt